In [59]:
import pandas as pd

In [60]:
logs = pd.read_csv('log.csv')

In [61]:
logs

,job_id,job_time,backend,shots,archt,qubits,layers,samples,rotations,entangler,mixer,driver,driver_per,initial_qaoa,sabre,mapomatic,DD
0,fa1bb922-f6ba-4d24-bb3a-fc86de339fbe,"03/06/2022, 22:16:03",simulator,100,linear,"[1, 2, 3, 4]","[0, 1, 2, 3]",10,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False
1,486b46f8-3764-4970-8688-4c4ced9f7d2f,"03/06/2022, 22:16:04",simulator,100,linear,"[1, 2, 3, 4]","[0, 1, 2, 3]",10,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False
2,629a77691e5d5e8606df6d82,"03/06/2022, 23:04:41",ibmq_lima,100,linear,"[1, 2]","[1, 2]",10,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False
3,629a828c22557e212a6486ee,"03/06/2022, 23:52:12",ibm_perth,100,linear,"[1, 2]","[1, 2]",10,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False
4,629a83df16ca601a4b7e1dd5,"03/06/2022, 23:57:51",ibm_perth,100,linear,"[1, 2]","[1, 2]",10,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,1e7f80fd-1e8f-431d-a731-d9884c1674d0,"08/06/2022, 17:07:44",simulator,100000,linear,[10],"[0, 1, 2, 3, 4, 5]",50,['ry'],cz,rx,rzz,ryy,hadamards,True,False,False
133,62a61d16e3530c5a6ff29bf5,"12/06/2022, 19:06:30",ibmq_kolkata,1000,linear,[5],"[3, 4, 5, 6, 7, 8]",50,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False
134,62a61d39e3530c6678f29bf8,"12/06/2022, 19:07:04",ibmq_kolkata,1000,linear,[5],"[9, 10, 11, 12, 13]",50,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False
135,62ac8c0821544e1e7302a073,"17/06/2022, 16:13:28",ibmq_mumbai,1000,linear,"[3, 5]","[0, 1, 2]",50,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False
136,62ac8c2c22eb882eb7ab878c,"17/06/2022, 16:14:04",ibmq_mumbai,1000,linear,"[7, 10]","[0, 1, 2]",50,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False

In [57]:
target = 'ibmq_mumbai'
row    = logs.loc[(logs['backend']==target)]

In [58]:
row

,job_id,job_time,backend,shots,archt,qubits,layers,samples,rotations,entangler,mixer,driver,driver_per,initial_qaoa,sabre,mapomatic,DD
14,629b9669a38471eb654514f4,"04/06/2022, 19:29:13",ibmq_mumbai,1000,linear,"[7, 10]","[0, 1, 2]",50,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False
21,629b985216ca6046d17e23c3,"04/06/2022, 19:37:22",ibmq_mumbai,1000,linear,"[3, 5]","[0, 1, 2]",50,['ry'],cx,rx,rzz,ryy,hadamards,True,True,False