In [1]:
import pandas as pd
from ast import literal_eval

In [2]:
exp_stats = pd.read_csv('exp_stats.csv')

In [3]:
exp_stats

,exp_id,job_id,backend,archt,qubits,layers,parameters,depth,cnots,operator,...,p=5,p=10,p=25,p=50,p=75,p=90,p=95,p=99,p=100,shots
0,4fb575bc-71aa-407f-bf9b-debd83492190,['5b192fab-6b6c-4eca-84ff-82de4ebdd516'],aer_simulator,linear,5,1,10,"[9, 9, 9, 9, 9, 8, 9, 9, 9, 9, 9, 8, 8, 9, 9, 8]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",Paulis,...,0.002276,0.003168,0.007054,0.012030,0.021111,0.030503,0.035647,0.054652,0.061100,1000.0
1,30cfc81b-a2c8-45e3-88ab-009861cac21a,['4f212fdd-c96f-496c-b458-66fb338123d2'],aer_simulator,linear,5,1,10,"[6, 13]","[0, 1]",Sato21,...,0.001013,0.001822,0.004875,0.009852,0.023135,0.035834,0.038644,0.046359,0.051470,1000.0
2,4afac88b-c7c7-4dd0-b1b2-1971ef8bebab,['ef4e8b91-be94-4e76-a8cc-0e6cfd2769bf'],aer_simulator,linear,5,1,10,"[6, 8, 9, 10, 11]","[0, 2, 3, 4, 5]",SatoLiu21,...,0.001354,0.002571,0.005178,0.009472,0.033925,0.045483,0.053126,0.099116,0.113395,1000.0
3,9257207d-3b84-49f6-92c8-8a8d92fcee26,['c0ce2f77-39cd-4a31-908e-5cb78863edec'],aer_simulator,linear,5,1,10,"[6, 187]","[0, 100]",SatoLiu21_efficient,...,0.000710,0.001668,0.005316,0.009985,0.023504,0.036749,0.045399,0.074321,0.074612,1000.0
4,73bc23a0-ec07-40f6-92ed-ac374a48d7c6,['62c9a17e1c9300c5ad09ef87'],ibmq_ehningen,linear,5,1,10,"[24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 2...","[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]",Paulis,...,0.044562,0.057951,0.070329,0.137711,0.180297,0.214755,0.243973,0.278582,0.287235,1000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,2389d4c3-174e-4755-8580-a3a09b206e70,['62cd7960fdb4a8f01542b4ee'],ibmq_ehningen,linear_alternating,5,3,29,"[44, 360]","[12, 187]",constant,...,0.017474,0.019408,0.101198,0.269649,0.365520,0.937453,1.212092,1.446443,1.505031,100.0
388,49bc577a-5786-42ab-9671-067d9ec93026,['62cd7975800aadb62a4cef2d'],ibmq_ehningen,linear_alternating,5,3,29,"[44, 45, 52, 62, 67]","[12, 14, 16, 18, 20]",constant,...,0.017474,0.019408,0.101198,0.269649,0.365520,0.937453,1.212092,1.446443,1.505031,10000.0
389,4cd4dba3-d96f-4ce9-9865-4ca544390dba,['62cd798a1c93004e9e09f304'],ibmq_ehningen,linear_alternating,5,3,29,"[44, 360]","[12, 187]",constant,...,0.017474,0.019408,0.101198,0.269649,0.365520,0.937453,1.212092,1.446443,1.505031,10000.0
390,9fc60058-d536-46ec-8e51-871ade6912fc,['62cd799ffdb4a8b9d342b4ef'],ibmq_ehningen,linear_alternating,5,3,29,"[44, 45, 52, 62, 67]","[12, 14, 16, 18, 20]",constant,...,0.017474,0.019408,0.101198,0.269649,0.365520,0.937453,1.212092,1.446443,1.505031,100000.0
391,909e00c3-2f01-443a-9f60-c3c61ba6b7f4,['62cd79b11c93007f7709f305'],ibmq_ehningen,linear_alternating,5,3,29,"[44, 360]","[12, 187]",constant,...,0.017474,0.019408,0.101198,0.269649,0.365520,0.937453,1.212092,1.446443,1.505031,100000.0

In [64]:
backend    = 'aer_simulator'
operator   = 'Paulis'
archt      = 'linear_alternating'
shots      = 10000
num_qubits = 5
num_layers = 3
row        = exp_stats.loc[   (exp_stats['backend']==backend)
                        & (exp_stats['relative']==True)
                        & (exp_stats['operator']==operator)
                        & (exp_stats['qubits']==num_qubits)
                        & (exp_stats['layers']==num_layers)
                        #& (exp_stats['shots']==shots)
                        & (exp_stats['samples']==18)
                        & (exp_stats['archt']==archt)
                        & (exp_stats['rotations']=="['ry']")
                        & (exp_stats['sabre']==True)
                        & (exp_stats['mapomatic']==False)
                        & (exp_stats['DD']==False)
                        & (exp_stats['mem']==False)]

In [65]:
reduced = row[['backend', 'operator', 'archt', 'qubits', 'layers', 'parameters', 'cnots', 'shots', 'samples',
               'mean', 'std']]
reduced

,backend,operator,archt,qubits,layers,parameters,cnots,shots,samples,mean,std
59,aer_simulator,Paulis,linear_alternating,5,3,29,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",1000.0,18,0.022307,0.023998
259,aer_simulator,Paulis,linear_alternating,5,3,29,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",10.0,18,0.140890,0.087482
267,aer_simulator,Paulis,linear_alternating,5,3,29,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",100.0,18,0.051768,0.035167
287,aer_simulator,Paulis,linear_alternating,5,3,29,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",10000.0,18,0.004609,0.004194
300,aer_simulator,Paulis,linear_alternating,5,3,29,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",100000.0,18,0.002407,0.002153

In [66]:
aftermax = reduced.cnots.apply(literal_eval).apply(max)
aftermax = pd.concat([reduced.drop('cnots',axis=1), aftermax],axis=1)
aftermax

,backend,operator,archt,qubits,layers,parameters,shots,samples,mean,std,cnots
59,aer_simulator,Paulis,linear_alternating,5,3,29,1000.0,18,0.022307,0.023998,0
259,aer_simulator,Paulis,linear_alternating,5,3,29,10.0,18,0.140890,0.087482,0
267,aer_simulator,Paulis,linear_alternating,5,3,29,100.0,18,0.051768,0.035167,0
287,aer_simulator,Paulis,linear_alternating,5,3,29,10000.0,18,0.004609,0.004194,0
300,aer_simulator,Paulis,linear_alternating,5,3,29,100000.0,18,0.002407,0.002153,0

In [67]:
sort = aftermax.sort_values(by=['qubits', 'layers', 'shots'])
sort

,backend,operator,archt,qubits,layers,parameters,shots,samples,mean,std,cnots
259,aer_simulator,Paulis,linear_alternating,5,3,29,10.0,18,0.140890,0.087482,0
267,aer_simulator,Paulis,linear_alternating,5,3,29,100.0,18,0.051768,0.035167,0
59,aer_simulator,Paulis,linear_alternating,5,3,29,1000.0,18,0.022307,0.023998,0
287,aer_simulator,Paulis,linear_alternating,5,3,29,10000.0,18,0.004609,0.004194,0
300,aer_simulator,Paulis,linear_alternating,5,3,29,100000.0,18,0.002407,0.002153,0

In [68]:
sort_reset = sort.reset_index(drop=True)
sort_reset

,backend,operator,archt,qubits,layers,parameters,shots,samples,mean,std,cnots
0,aer_simulator,Paulis,linear_alternating,5,3,29,10.0,18,0.140890,0.087482,0
1,aer_simulator,Paulis,linear_alternating,5,3,29,100.0,18,0.051768,0.035167,0
2,aer_simulator,Paulis,linear_alternating,5,3,29,1000.0,18,0.022307,0.023998,0
3,aer_simulator,Paulis,linear_alternating,5,3,29,10000.0,18,0.004609,0.004194,0
4,aer_simulator,Paulis,linear_alternating,5,3,29,100000.0,18,0.002407,0.002153,0

In [69]:
duplicates = sort_reset.drop_duplicates(subset=['shots'], keep='last')
duplicates

,backend,operator,archt,qubits,layers,parameters,shots,samples,mean,std,cnots
0,aer_simulator,Paulis,linear_alternating,5,3,29,10.0,18,0.140890,0.087482,0
1,aer_simulator,Paulis,linear_alternating,5,3,29,100.0,18,0.051768,0.035167,0
2,aer_simulator,Paulis,linear_alternating,5,3,29,1000.0,18,0.022307,0.023998,0
3,aer_simulator,Paulis,linear_alternating,5,3,29,10000.0,18,0.004609,0.004194,0
4,aer_simulator,Paulis,linear_alternating,5,3,29,100000.0,18,0.002407,0.002153,0

In [70]:
duplicates.to_csv(backend+'_'+archt+'_'+operator+'_'+'q'+str(num_qubits)+'l'+str(num_layers)+'_shots'+'.csv')